### ISSUE TITLE
Linux 0.1.2 x86_64 build Unable to load shared library 'libSkiaSharp"

### ISSUE THREAD

**Issue by JoshuaPettus** [Shivansps/Knossos.NET#5]
Hi when trying to run the latest version on linux I get what appears to be some dotnet error
I'm using Fedora 38.  

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.PlatformRenderInterface..ctor(Nullable`1 maxResourceBytes)
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
   at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Knossos.NET.Program.Main(String[] args)
Aborted (core dumped)
```
I know the library is included with the bundle so not sure what gives

From a google search, I tried running 
> readelf -d libSkiaSharp.so

but I don't see anything out of the ordinary

```
Dynamic section at offset 0x7a1708 contains 34 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libfontconfig.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libSkiaSharp.so.88.1.0]
 0x000000000000000c (INIT)               0x744d0
 0x000000000000000d (FINI)               0x643390
 0x0000000000000019 (INIT_ARRAY)         0x789090
 0x000000000000001b (INIT_ARRAYSZ)       88 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x7890e8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x228
 0x000000006ffffef5 (GNU_HASH)           0x2478
 0x0000000000000005 (STRTAB)             0xac50
 0x0000000000000006 (SYMTAB)             0x3f60
 0x000000000000000a (STRSZ)              26426 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x7b2fe8
 0x0000000000000002 (PLTRELSZ)           5232 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x73060
 0x000000006ffffef6 (TLSDESC_PLT)        0x75270
 0x000000006ffffef7 (TLSDESC_GOT)        0x7b2fe0
 0x0000000000000007 (RELA)               0x11d58
 0x0000000000000008 (RELASZ)             398088 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffc (VERDEF)             0x11ca0
 0x000000006ffffffd (VERDEFNUM)          2
 0x000000006ffffffe (VERNEED)            0x11cd8
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x1138a
 0x000000006ffffff9 (RELACOUNT)          16576
 0x0000000000000000 (NULL)               0x0
```

**Comment by Shivansps** [comment]
Yes, somehow the two .so lib files produced during compilation were broken somehow. They were smaller that what they should have been.
Ive updated the release files for Linux_x64, please check.

**Comment by JoshuaPettus** [comment]
Yup that was it!  Thanks!
